<a href="https://colab.research.google.com/github/Auta01/Tensorflow-cases/blob/main/Tensorflow%20fundamental%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Importing the tensor library
import tensorflow as tf

In [3]:
#Creating tensor with tf.variable

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [4]:
#let try .assign()
changeable_tensor[0].assign = 7
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

CREATING RANDOM TENSOR WITH TENSORFLOW

In [5]:
#Creating Random Tensors
random_1 = tf.random.Generator.from_seed(7) # set speeed for reproducility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))

In [6]:
#Are they equal?
random_1 , random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [7]:
not_shuffled = tf.constant([[10,10],
                            [7,6],
                            [5,5]])

In [8]:
#shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  6],
       [10, 10],
       [ 5,  5]], dtype=int32)>

In [9]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed= 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 10],
       [ 7,  6],
       [ 5,  5]], dtype=int32)>

Creating tensors with numpy


In [10]:
tf.ones([10,4])

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [11]:
tf.zeros([5,5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [12]:
#you can also turn numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [13]:
A = tf.constant(numpy_A, shape =(3,8))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

Getting information from tensors


*   shape
*   Axis
*   Rank
*   Size



In [14]:
#Create a rank 4 tensor
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [15]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [16]:
2*3*4*5

120

In [17]:
#Getting  various attribute of our tensor
print('Datatype of every element:',rank_4_tensor.dtype)
print('Number of dimensions rank:',rank_4_tensor.ndim)
print('shape of tensor:',rank_4_tensor.shape)
print('Element along the 0 axis:',rank_4_tensor.shape[0])
print('Elements along the last axis:', rank_4_tensor.shape[-1])
print('Total number of elements in our tensor:', tf.size(rank_4_tensor))
print('Total number of elements in our tensor:',tf.size(rank_4_tensor).numpy)

Datatype of every element: <dtype: 'float32'>
Number of dimensions rank: 4
shape of tensor: (2, 3, 4, 5)
Element along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=120>>


In [18]:
## indexing can be index just like python list
#get the first 2 element of each dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [19]:
#Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [20]:
#create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],
                             [7,8]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [21]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7,  8]], dtype=int32)>

In [22]:
rank_2_tensor [:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 8], dtype=int32)>

In [23]:
#Adding extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [ 8]]], dtype=int32)>

In [24]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand to the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [ 8]]], dtype=int32)>

In [25]:
tf.expand_dims(rank_2_tensor,axis=0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 7,  8]]], dtype=int32)>

In [26]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7,  8]], dtype=int32)>

In [27]:
###Manipulating tensor (tensor operation)
#Basic operation
tensor = tf.constant([[10,7],[3,4]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [28]:
#multiplication
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [29]:
tensor - 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [30]:
## we can use the tensorflow built in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [31]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [33]:
#Matrix mutiplication in tensorfloww
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [34]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [35]:
#Matrix multiplication with python operation '@'
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [36]:
tensor.shape

TensorShape([2, 2])

In [37]:
#Create a tensor with (3,2) tensor
x = tf.constant([[1,2],
                 [2,3],
                 [7,4]])
y = tf.constant([[5,5],
                 [6,7],
                 [8,9]])


In [40]:
#Try to multiply the tensor of same shape
#let try reshape y
tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[5, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [43]:
#try to  matrix multiply by x reshaped y
x@ tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[19, 21, 24],
       [31, 34, 39],
       [63, 67, 78]], dtype=int32)>

In [44]:
tf.matmul(x, tf.reshape(y, shape=(2,3) ))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[19, 21, 24],
       [31, 34, 39],
       [63, 67, 78]], dtype=int32)>

In [47]:
tf.reshape(x,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 2],
       [3, 7, 4]], dtype=int32)>

In [48]:
tf.matmul(y,tf.reshape(x, shape= (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[20, 45, 30],
       [27, 61, 40],
       [35, 79, 52]], dtype=int32)>

In [52]:
#can do same with transpose
x, tf.transpose(x) , tf.reshape(x, shape =(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 3],
        [7, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 7],
        [2, 3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 2],
        [3, 7, 4]], dtype=int32)>)

In [53]:
#try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(x), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[73, 82],
       [60, 67]], dtype=int32)>

In [55]:
#The dot product
#Matrix multiplication is also referred to as dot product
#perform the dot product on x and y (required x or t to be transposed)

tf.tensordot(tf.transpose(x),y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[73, 82],
       [60, 67]], dtype=int32)>

In [57]:
tf.matmul(x, tf.reshape(y, shape= (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[19, 21, 24],
       [31, 34, 39],
       [63, 67, 78]], dtype=int32)>

In [61]:
#Checking the the value of y , reshape y and transposed y
print('normal y:',y)

print('y reshaped:',tf.reshape(y,(2,3)))

print('Yy transposed :',tf.transpose(y))

normal y: tf.Tensor(
[[5 5]
 [6 7]
 [8 9]], shape=(3, 2), dtype=int32)
y reshaped: tf.Tensor(
[[5 5 6]
 [7 8 9]], shape=(2, 3), dtype=int32)
Yy transposed : tf.Tensor(
[[5 6 8]
 [5 7 9]], shape=(2, 3), dtype=int32)


In [63]:
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[15, 20, 26],
       [25, 33, 43],
       [55, 70, 92]], dtype=int32)>